import { defineConfig } from 'vitest/config';
import { sveltekit } from '@sveltejs/kit/vite';
import { svelteTesting } from '@testing-library/svelte/vite';
import Icons from 'unplugin-icons/vite';
import path from 'path';

export default defineConfig({
	plugins: [
		sveltekit(),
		svelteTesting(),
		Icons({
			compiler: 'svelte',
			defaultClass: 'icon'
		})
	],
	test: {
		globals: true,
		environment: 'jsdom',
		// citeproc parses a CSL style from XML on every engine construction, and
		// the citation tests build a lot of engines — the bibliography-across-
		// styles test alone parses five large files and takes over a second on a
		// developer machine. Vitest's 5s default left no headroom on a two-core CI
		// runner, where it timed out. Long enough for real work, short enough that
		// a genuinely hung test still fails rather than hanging the job.
		testTimeout: 30_000,
		hookTimeout: 60_000,
		include: ['src/**/*.{test,spec}.{js,ts,svelte}', 'scripts/**/*.test.mjs'],
		setupFiles: ['./vitest.setup.ts'],
		coverage: {
			provider: 'v8',
			reporter: ['text-summary', 'json', 'html'],
			// Report on our own source only. `~icons/*` are virtual modules generated by
			// unplugin-icons and would otherwise dominate the report with ~150 entries.
			include: ['src/**/*.{ts,svelte}'],
			exclude: [
				'node_modules/**',
				'src-tauri/**',
				'static/**',
				'**/*.d.ts',
				'**/~icons/**',
				'src/**/*.{test,spec}.{js,ts,svelte}'
			]
		}
	},
	resolve: {
		alias: {
			$lib: path.resolve('./src/lib'),
			$utils: path.resolve('./src/utils'),
			$types: path.resolve('./src/types'),
			$ui: path.resolve('./src/lib/ui')
		}
	}
});
