// Generated by tauri-specta from src-tauri (ADR 011). Do not edit.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	readDirectory: (path: string) => typedError<FileItem[], AppError>(__TAURI_INVOKE("read_directory", { path })),
	/**
	 *  Show the folder Erti's log is in, in the file manager (M1a-12 AC-5).
	 * 
	 *  From Rust rather than the opener plugin's `open_path`, which would need a
	 *  capability reaching the log directory for one button.
	 */
	openLogFolder: () => typedError<null, AppError>(__TAURI_INVOKE("open_log_folder")),
	readPdfFile: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("read_pdf_file", { path })),
	embedChunks: (chunks: string[]) => typedError<EmbeddingResult[], AppError>(__TAURI_INVOKE("embed_chunks", { chunks })),
	/**  Open the source library, creating it if this is the first run. */
	openLibrary: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("open_library", { path })),
	/**  Open a project folder, creating `<root>/.erti/project.db` if needed. */
	openProject: (root: string) => typedError<null, AppError>(__TAURI_INVOKE("open_project", { root })),
	/**
	 *  Add a cited source this library lacks, from the manuscript's snapshot, and
	 *  put it in the open project (M1a-8 AC-6). The webview guards the snapshot as
	 *  CSL first (M1b-10); this refuses anything that isn't a JSON object or an id
	 *  that couldn't be a source's.
	 */
	addSourceFromManuscript: (id: string, cslJson: string) => typedError<boolean, AppError>(__TAURI_INVOKE("add_source_from_manuscript", { id, cslJson })),
	/**
	 *  Which of these folders are still Erti projects: there, with the
	 *  `.erti/project.db` opening them left behind.
	 * 
	 *  The landing screen marks a moved or deleted recent project, and used to ask
	 *  the fs plugin whether each path existed, which needed read access to all of
	 *  `$HOME`. This answers only the question it had, and only about project
	 *  folders: an arbitrary path gets `false`, so it says nothing about the disk.
	 */
	recentProjectsPresent: (paths: string[]) => typedError<boolean[], AppError>(__TAURI_INVOKE("recent_projects_present", { paths })),
	projectRoot: () => typedError<string, AppError>(__TAURI_INVOKE("project_root")),
	/**  Hash a file's contents. See `db::hash_file`. */
	hashFile: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("hash_file", { path })),
	/**
	 *  Record a source and add it to the open project.
	 * 
	 *  Returns true when this hash was new to the library, so the caller knows
	 *  whether the file still needs extracting and embedding, or was already done
	 *  for another project.
	 */
	registerSource: (sha256: string, path: string, fileName: string) => typedError<boolean, AppError>(__TAURI_INVOKE("register_source", { sha256, path, fileName })),
	/**  What this machine can do with a `.tex`. */
	detectTexToolchain: () => __TAURI_INVOKE<TexToolchain>("detect_tex_toolchain"),
	/**
	 *  Compile `main.tex` in a bundle directory.
	 * 
	 *  The log is returned either way. A TeX error is famously hard to read, but it
	 *  is the only thing that says what went wrong, and hiding it would leave the
	 *  user with "compilation failed" and nowhere to go.
	 */
	compileLatex: (directory: string, engine: string) => typedError<CompileResult, AppError>(__TAURI_INVOKE("compile_latex", { directory, engine })),
	sourcesNeedingIngest: () => typedError<string[], AppError>(__TAURI_INVOKE("sources_needing_ingest")),
	storeChunks: (sha256: string, chunks: NewChunk[]) => typedError<null, AppError>(__TAURI_INVOKE("store_chunks", { sha256, chunks })),
	markIngestFailed: (sha256: string, error: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_ingest_failed", { sha256, error })),
	setSourceMetadata: (sha256: string, cslJson: string, zoteroType: string | null, doi: string | null, resolvedVia: string) => typedError<null, AppError>(__TAURI_INVOKE("set_source_metadata", { sha256, cslJson, zoteroType, doi, resolvedVia })),
	/**  Sources in the open project, with project-local metadata overrides applied. */
	projectSources: () => typedError<Source[], AppError>(__TAURI_INVOKE("project_sources")),
	/**
	 *  Every alias in the library, alias → canonical (ADR 003).
	 * 
	 *  The webview resolves the ids a manuscript cites with this, so a citation
	 *  of a PDF's hash renders as the work the PDF was attached to.
	 */
	sourceAliases: () => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("source_aliases")),
	addToProject: (sha256: string) => typedError<null, AppError>(__TAURI_INVOKE("add_to_project", { sha256 })),
	setMetadataOverride: (sha256: string, cslJson: string) => typedError<null, AppError>(__TAURI_INVOKE("set_metadata_override", { sha256, cslJson })),
	/**
	 *  Rank chunks against a piece of text the user is writing.
	 * 
	 *  Embedding and scoring both happen here; only the top results cross the IPC
	 *  boundary, rather than the entire corpus as before.
	 */
	searchSources: (query: string, limit: number | null, includeLibrary: boolean | null) => typedError<ScoredChunk[], AppError>(__TAURI_INVOKE("search_sources", { query, limit, includeLibrary })),
	embeddingMeta: () => typedError<{
	model_id: string,
	dims: number,
} | null, AppError>(__TAURI_INVOKE("embedding_meta")),
	setEmbeddingMeta: (modelId: string, dims: number) => typedError<null, AppError>(__TAURI_INVOKE("set_embedding_meta", { modelId, dims })),
	/**
	 *  Import metadata from the pre-hybrid database, if one exists.
	 * 
	 *  The old database is only read, never modified — it stays on disk so nothing
	 *  is lost if the result is unsatisfactory.
	 */
	importLegacyMetadata: (legacyDbPath: string) => typedError<SalvageReport, AppError>(__TAURI_INVOKE("import_legacy_metadata", { legacyDbPath })),
	/**  Metadata previously resolved for this filename, if any. */
	legacyMetadataFor: (fileName: string) => typedError<string | null, AppError>(__TAURI_INVOKE("legacy_metadata_for", { fileName })),
	markLegacyConsumed: (fileName: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_legacy_consumed", { fileName })),
	saveAnnotation: (annotation: NewAnnotation) => typedError<null, AppError>(__TAURI_INVOKE("save_annotation", { annotation })),
	annotationsForSource: (sha256: string) => typedError<Annotation[], AppError>(__TAURI_INVOKE("annotations_for_source", { sha256 })),
	allAnnotations: (limit: number | null, offset: number | null) => typedError<Annotation[], AppError>(__TAURI_INVOKE("all_annotations", { limit, offset })),
	deleteAnnotation: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_annotation", { id })),
	/**  A work's notes and the marks on its files, for its Notes tab (M1b-8, UX-3). */
	workNotes: (id: string) => typedError<WorkNotes, AppError>(__TAURI_INVOKE("work_notes", { id })),
	/**  Write a note on a work, or rewrite one (M1b-8 AC-2, ADR 004). */
	saveSourceNote: (note: NewSourceNote) => typedError<null, AppError>(__TAURI_INVOKE("save_source_note", { note })),
	deleteSourceNote: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_source_note", { id })),
	deleteImportedAnnotations: (sha256: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_imported_annotations", { sha256 })),
	annotationLabels: () => typedError<AnnotationLabel[], AppError>(__TAURI_INVOKE("annotation_labels")),
	saveLabel: (label: AnnotationLabel) => typedError<null, AppError>(__TAURI_INVOKE("save_label", { label })),
	deleteLabel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_label", { id })),
	saveReadingPosition: (sha256: string, page: number, scroll: number | null, scale: string | null) => typedError<null, AppError>(__TAURI_INVOKE("save_reading_position", { sha256, page, scroll, scale })),
	readingPosition: (sha256: string) => typedError<number | null, AppError>(__TAURI_INVOKE("reading_position", { sha256 })),
	pathForSource: (sha256: string) => typedError<string | null, AppError>(__TAURI_INVOKE("path_for_source", { sha256 })),
	sourceForPath: (path: string) => typedError<string | null, AppError>(__TAURI_INVOKE("source_for_path", { path })),
	saveAnnotationImage: (id: string, png: number[]) => typedError<null, AppError>(__TAURI_INVOKE("save_annotation_image", { id, png })),
	annotationImage: (id: string) => typedError<number[] | null, AppError>(__TAURI_INVOKE("annotation_image", { id })),
	/**
	 *  Embed a mark's text so it can be found by meaning later.
	 * 
	 *  The embedding happens here rather than in the frontend for the same reason
	 *  search does: `embed_texts` is synchronous ONNX inference, and a 384-float
	 *  vector has no business crossing the IPC boundary in either direction when
	 *  only the database needs it.
	 * 
	 *  Skipped when the text has not changed. Recolouring a highlight or moving it
	 *  to another label should not cost an inference.
	 */
	embedAnnotation: (id: string, text: string) => typedError<boolean, AppError>(__TAURI_INVOKE("embed_annotation", { id, text })),
	/**
	 *  Give every mark that has none a vector, so it can be found by meaning.
	 * 
	 *  Marks are embedded as they are made, and that can fail quietly — a library
	 *  not open yet, a model still loading, a save racing a project switch. A
	 *  highlight must never be lost to a failed embedding, so the failure is
	 *  swallowed; the cost is that the mark is then missing from every search by
	 *  meaning with nothing to say so. This is the way back.
	 * 
	 *  Returns how many were embedded, so the caller can say what happened rather
	 *  than leave another silence.
	 */
	embedPendingAnnotations: () => typedError<number, AppError>(__TAURI_INVOKE("embed_pending_annotations")),
	/**
	 *  Find marks, by their words or by what they are about.
	 * 
	 *  Deliberately separate from `search_sources`. A passage from a paper and a
	 *  note the researcher wrote are not the same kind of thing — one is quotable,
	 *  the other is a judgement already made — and a 12-word note does not produce
	 *  a cosine score comparable with a 100-word passage, so merging the two into
	 *  one ranked list would be quietly wrong in a way nobody could see.
	 */
	searchAnnotations: (query: string, limit: number | null, semantic: boolean | null) => typedError<ScoredAnnotation[], AppError>(__TAURI_INVOKE("search_annotations", { query, limit, semantic })),
	/**
	 *  Search everything in the library by meaning: passages, marks and source
	 *  notes, in one ranked list, each result saying which it is (ADR 005).
	 * 
	 *  `kinds` narrows it (all three when left out), and only the open project's
	 *  works count unless `include_library`. Both apply before scoring, so a
	 *  narrower search still fills `limit`. The project's results come first.
	 */
	searchLibrary: (query: string, kinds: HitKind[] | null, limit: number | null, includeLibrary: boolean | null) => typedError<Hit[], AppError>(__TAURI_INVOKE("search_library", { query, kinds, limit, includeLibrary })),
	/**  What removing a source would delete, for the dialog that asks first. */
	sourceRemoval: (id: string) => typedError<SourceRemoval, AppError>(__TAURI_INVOKE("source_removal", { id })),
	/**
	 *  Add a source the researcher entered by hand (M1b-5, UX-2): a work with no
	 *  file, in the library and the open project.
	 * 
	 *  The id is made in the webview, as a mark's is (`crypto.randomUUID`), and
	 *  checked here: it has to be one no hash can be, so a PDF found later never
	 *  collides with it (ADR 003).
	 */
	addSourceByHand: (id: string, cslJson: string, zoteroType: string) => typedError<null, AppError>(__TAURI_INVOKE("add_source_by_hand", { id, cslJson, zoteroType })),
	/**
	 *  Remove a source from the library, with its files' records, marks and
	 *  notes (M1b-4). The PDFs stay where they are.
	 */
	removeSource: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_source", { id })),
	/**  Attach the PDF at `path` to the work `work` (M1b-7, ADR 003). */
	attachFile: (work: string, path: string) => typedError<AttachedFile, AppError>(__TAURI_INVOKE("attach_file", { work, path })),
	/**  A work's files, for its sidebar's File tab (M1b-7 AC-3). */
	sourceFiles: (id: string) => typedError<SourceFile[], AppError>(__TAURI_INVOKE("source_files", { id })),
	restoreDefaultLabels: () => typedError<number, AppError>(__TAURI_INVOKE("restore_default_labels")),
	nameLabelsAfterColours: () => typedError<number, AppError>(__TAURI_INVOKE("name_labels_after_colours")),
};

/* Types */
/**
 *  A reading mark: a highlight, an area snapshot, or a note pinned to a page.
 * 
 *  Anchored twice over. `rects` draws it immediately and survives zoom, because
 *  it is stored in PDF user space rather than screen pixels. `quote` with the
 *  text either side finds it again when the geometry stops agreeing, and is
 *  also what makes the passage searchable rather than merely positioned.
 */
export type Annotation = {
	id: string,
	sha256: string,
	/**  'highlight' | 'area' | 'page-note' */
	kind: string,
	label_id: string | null,
	page: number,
	/**  JSON array of `{x, y, w, h}` in PDF user space; None for a page note. */
	rects: string | null,
	quote: string | null,
	prefix: string | null,
	suffix: string | null,
	char_start: number | null,
	char_end: number | null,
	note: string | null,
	/**  'fill' | 'underline' — how the mark is drawn, not what it means. */
	style: string,
	/**  The page number the paper itself prints, when it differs from the sheet. */
	page_label: string | null,
	/**
	 *  'erti' | 'imported' — so highlights brought in from Zotero or Preview
	 *  can be told apart, and undone in one action.
	 */
	origin: string,
	created_at: string,
	updated_at: string,
};

/**  What a highlight colour means. */
export type AnnotationLabel = {
	id: string,
	name: string,
	/**
	 *  `H S% L%`, matching the theme tokens rather than a hex string, so a
	 *  label sits in the same colour system as the rest of the interface.
	 */
	colour: string,
	position: number,
	enabled: boolean,
};

/**  An error on its way to the webview. */
export type AppError = {
	kind: ErrorKind,
	/**  A sentence a person can read, already saying what to do where possible. */
	message: string,
};

/**  A file attached to a work, and what's left to do with it (M1b-7). */
export type AttachedFile = {
	/**  The file's own hash, which reading it goes under. */
	sha256: string,
	file_name: string,
	/**  False when the library has read it already, for another project. */
	needs_ingest: boolean,
	/**
	 *  The source this file was until now, by title or file name, when the
	 *  library had it as one of its own: its citations now render as the work
	 *  it joined, and its row in any project is that work's.
	 */
	merged: string | null,
	/**
	 *  It was already this source's file, found somewhere new: the place is
	 *  recorded, and Open and Show in folder use it.
	 */
	found_again: boolean,
};

export type CompileResult = {
	ok: boolean,
	/**  Path to the PDF, when one was produced. */
	pdf: string | null,
	/**  The engine's output, kept whether or not it succeeded. */
	log: string,
};

/**
 *  The model that produced the stored vectors, if any are stored yet.
 *  Which model produced the stored vectors.
 */
export type EmbeddingMeta = {
	model_id: string,
	dims: number,
};

export type EmbeddingResult = {
	chunk_text: string,
	embedding: (number | null)[],
};

/**  What sort of failure this was, for the interface to act on. */
export type ErrorKind = 
/**  A file, source or record that isn't there (any more). */
"NotFound" | 
/**  The operating system refused; the message says which setting fixes it. */
"PermissionDenied" | 
/**  The request itself was malformed or out of range. */
"InvalidInput" | 
/**  It clashes with the current state: already exists, not open yet. */
"Conflict" | 
/**  Some other filesystem failure. */
"Io" | 
/**  The library or project database failed. */
"Database" | 
/**  The embedding model failed. */
"Model" | 
/**  A network request failed. */
"Network" | 
/**  A bug: something that should not happen. */
"Internal";

export type FileItem = {
	name: string,
	path: string,
	is_dir: boolean,
	children: FileItem[] | null,
};

/**
 *  One result from the index, whatever kind of row it is (ADR 005).
 * 
 *  `kind` says which, and `hit` holds the row as each kind's own search
 *  returns it. Adjacent rather than flattened: a mark already has a field
 *  called `kind` (highlight, area, page note).
 */
export type Hit = { kind: "chunk"; hit: ScoredChunk } | { kind: "annotation"; hit: ScoredAnnotation } | { kind: "source_note"; hit: ScoredSourceNote };

/**
 *  What a row of the index is.
 * 
 *  Kept apart in a result, never blended: a passage from a paper is quotable,
 *  a mark or a note is a judgement already made (see `search_annotations`).
 */
export type HitKind = "chunk" | "annotation" | "source_note";

/**
 *  An annotation on its way in. The id is chosen by the caller so the same
 *  record keeps its identity through an export and back.
 */
export type NewAnnotation = {
	id: string,
	sha256: string,
	kind: string,
	label_id?: string | null,
	page: number,
	rects?: string | null,
	quote?: string | null,
	prefix?: string | null,
	suffix?: string | null,
	char_start?: number | null,
	char_end?: number | null,
	note?: string | null,
	style?: string | null,
	page_label?: string | null,
	origin?: string | null,
};

export type NewChunk = {
	text: string,
	embedding: (number | null)[],
	page_start?: number | null,
	page_end?: number | null,
	section?: string | null,
	char_start?: number | null,
	char_end?: number | null,
};

/**
 *  A source note on its way in (M1b-8, ADR 004). The id is the caller's, as a
 *  mark's is, so a note keeps it through an export and back.
 */
export type NewSourceNote = {
	id: string,
	/**  Any of the work's ids: the note is kept under the work's own. */
	sha256: string,
	/**  Markdown. May be empty when there's a quote. */
	body: string,
	quote?: string | null,
	/**  The page as the paper prints it. */
	page_label?: string | null,
	label_id?: string | null,
};

export type SalvageReport = {
	/**  Rows carried forward. */
	imported: number,
	/**
	 *  Rows a previous run already carried forward. Reported separately so a
	 *  repeat launch does not claim new work.
	 */
	already_present: number,
	/**  Rows skipped because their metadata was a `'{}'` placeholder or absent. */
	skipped_empty: number,
	/**  Files in the old database that were registered but never processed. */
	skipped_unprocessed: number,
};

/**  A mark, ranked against something the researcher is looking for. */
export type ScoredAnnotation = {
	/**  Cosine similarity for a semantic search; 1.0 for a literal match. */
	similarity: number | null,
	/**
	 *  The work the mark's paper belongs to, for citing it (ADR 003). The
	 *  annotation's own `sha256` stays the file's, for "Show in PDF".
	 */
	source_id: string,
	/**  False when the mark is on a paper outside the open project's source set. */
	in_project: boolean,
	/**  The paper's filename, so a result can name where it came from. */
	file_name: string | null,
} & Annotation;

export type ScoredChunk = {
	/**
	 *  The file the passage is in, which "Show in PDF" opens. Not for citing:
	 *  a file attached to a work is an alias of it (ADR 003).
	 */
	sha256: string,
	/**
	 *  The work the passage belongs to: the id to cite, to add to a project
	 *  and to read metadata from.
	 */
	source_id: string,
	/**
	 *  Position of the chunk within its source. `(sha256, idx)` is the chunk's
	 *  primary key, and the only stable identity a result has — two chunks from
	 *  one PDF share a hash.
	 */
	idx: number,
	text: string,
	page_start: number | null,
	section: string | null,
	similarity: number | null,
	/**  False when the chunk comes from outside the current project's source set. */
	in_project: boolean,
};

/**  A source note, ranked against something the researcher is looking for. */
export type ScoredSourceNote = {
	similarity: number | null,
	/**  The work the note is about, resolved (ADR 003). */
	source_id: string,
	/**  False when the work is outside the open project's source set. */
	in_project: boolean,
} & SourceNote;

export type Source = {
	/**
	 *  The work's canonical id (ADR 003): a file's hash, or `erti:<uuid>` for
	 *  a work with no file of its own.
	 */
	sha256: string,
	file_name: string,
	path: string | null,
	/**
	 *  Whose file `path` is: the work's own hash, or the hash of a PDF attached
	 *  to it. Ingesting that file goes under this id, never under `sha256`, or
	 *  a PDF's chunks and extracted metadata would land on the work.
	 */
	file_sha256: string | null,
	/**  CSL-JSON, with any project-local override already applied. */
	csl_json: string | null,
	zotero_type: string | null,
	doi: string | null,
	resolved_via: string | null,
	/**
	 *  The work's own state: whether it can be cited. A work entered by hand
	 *  is `ready` while a PDF attached to it is still being read.
	 */
	state: string,
	last_error: string | null,
	/**
	 *  The ingest state of the file at `path`, which for an attached PDF is
	 *  not the work's (M1b-7 AC-1). None when the work has no file.
	 */
	file_state: string | null,
	file_error: string | null,
};

/**  One file of a work, for its sidebar's File tab (M1b-7 AC-3). */
export type SourceFile = {
	/**  The file's own hash: the work's id, or an attached file's. */
	sha256: string,
	file_name: string,
	/**
	 *  Where it was last found, or where it was last seen when it can't be
	 *  found anywhere now.
	 */
	path: string,
	/**  False when no place it was seen still has a file. */
	found: boolean,
	/**  Its ingest state: whether it has been read yet, or failed. */
	state: string,
	last_error: string | null,
};

/**  A note about a work as a whole (ADR 004). */
export type SourceNote = {
	id: string,
	/**
	 *  The work's id. Always canonical when written (`alias_source` moves a
	 *  work's notes with it).
	 */
	sha256: string,
	/**  Markdown. Empty when the note is only the quote. */
	body: string,
	quote: string | null,
	/**  The page as the paper prints it. */
	page_label: string | null,
	label_id: string | null,
	created_at: string,
	updated_at: string,
};

/**
 *  What removing a work would take with it, for the dialog that asks first
 *  (docs/ux.md UX-4).
 */
export type SourceRemoval = {
	/**  Source notes, and page notes on its files. */
	notes: number,
	/**  Highlights and area snapshots on its files. */
	highlights: number,
	/**
	 *  Everywhere its files have been seen, the work's own and every attached
	 *  one's: any inside the project folder is read again by the next scan.
	 */
	paths: string[],
};

export type TexToolchain = {
	/**  The engine found, if any. */
	engine: string | null,
	/**  Whether BibTeX or Biber is available to resolve citations. */
	bibliography: string | null,
};

/**
 *  Everything noted on a work (UX-3's Notes tab): its own notes, and the marks
 *  on each of its files (ADR 003), so a book's tab shows the highlights made in
 *  the PDF attached to it.
 */
export type WorkNotes = {
	/**  In the order they were first written. */
	notes: SourceNote[],
	/**  By page, as a file's own marks are. */
	marks: Annotation[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

