// Generated by tauri-specta from src-tauri (ADR 011). Do not edit.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	readDirectory: (path: string) => typedError<FileItem[], AppError>(__TAURI_INVOKE("read_directory", { path })),
	readPdfFile: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("read_pdf_file", { path })),
	embedChunks: (chunks: string[]) => typedError<EmbeddingResult[], AppError>(__TAURI_INVOKE("embed_chunks", { chunks })),
	/**  Open the source library, creating it if this is the first run. */
	openLibrary: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("open_library", { path })),
	/**  Open a project folder, creating `<root>/.erti/project.db` if needed. */
	openProject: (root: string) => typedError<null, AppError>(__TAURI_INVOKE("open_project", { root })),
	/**
	 *  Which of these folders are still Erti projects: there, with the
	 *  `.erti/project.db` opening them left behind.
	 * 
	 *  The landing screen marks a moved or deleted recent project, and used to ask
	 *  the fs plugin whether each path existed, which needed read access to all of
	 *  `$HOME`. This answers only the question it had, and only about project
	 *  folders: an arbitrary path gets `false`, so it says nothing about the disk.
	 */
	recentProjectsPresent: (paths: string[]) => __TAURI_INVOKE<boolean[]>("recent_projects_present", { paths }),
	projectRoot: () => typedError<string, AppError>(__TAURI_INVOKE("project_root")),
	/**  Hash a file's contents. See `db::hash_file`. */
	hashFile: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("hash_file", { path })),
	/**
	 *  Record a source and add it to the open project.
	 * 
	 *  Returns true when this hash was new to the library, so the caller knows
	 *  whether the file still needs extracting and embedding, or was already done
	 *  for another project.
	 */
	registerSource: (sha256: string, path: string, fileName: string) => typedError<boolean, AppError>(__TAURI_INVOKE("register_source", { sha256, path, fileName })),
	/**  What this machine can do with a `.tex`. */
	detectTexToolchain: () => __TAURI_INVOKE<TexToolchain>("detect_tex_toolchain"),
	/**
	 *  Compile `main.tex` in a bundle directory.
	 * 
	 *  The log is returned either way. A TeX error is famously hard to read, but it
	 *  is the only thing that says what went wrong, and hiding it would leave the
	 *  user with "compilation failed" and nowhere to go.
	 */
	compileLatex: (directory: string, engine: string) => typedError<CompileResult, AppError>(__TAURI_INVOKE("compile_latex", { directory, engine })),
	sourcesNeedingIngest: () => typedError<string[], AppError>(__TAURI_INVOKE("sources_needing_ingest")),
	storeChunks: (sha256: string, chunks: NewChunk[]) => typedError<null, AppError>(__TAURI_INVOKE("store_chunks", { sha256, chunks })),
	markIngestFailed: (sha256: string, error: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_ingest_failed", { sha256, error })),
	setSourceMetadata: (sha256: string, cslJson: string, zoteroType: string | null, doi: string | null, resolvedVia: string) => typedError<null, AppError>(__TAURI_INVOKE("set_source_metadata", { sha256, cslJson, zoteroType, doi, resolvedVia })),
	/**  Sources in the open project, with project-local metadata overrides applied. */
	projectSources: () => typedError<Source[], AppError>(__TAURI_INVOKE("project_sources")),
	addToProject: (sha256: string) => typedError<null, AppError>(__TAURI_INVOKE("add_to_project", { sha256 })),
	setMetadataOverride: (sha256: string, cslJson: string) => typedError<null, AppError>(__TAURI_INVOKE("set_metadata_override", { sha256, cslJson })),
	/**
	 *  Rank chunks against a piece of text the user is writing.
	 * 
	 *  Embedding and scoring both happen here; only the top results cross the IPC
	 *  boundary, rather than the entire corpus as before.
	 */
	searchSources: (query: string, limit: number | null, includeLibrary: boolean | null) => typedError<ScoredChunk[], AppError>(__TAURI_INVOKE("search_sources", { query, limit, includeLibrary })),
	embeddingMeta: () => typedError<{
	model_id: string,
	dims: number,
} | null, AppError>(__TAURI_INVOKE("embedding_meta")),
	setEmbeddingMeta: (modelId: string, dims: number) => typedError<null, AppError>(__TAURI_INVOKE("set_embedding_meta", { modelId, dims })),
	/**
	 *  Import metadata from the pre-hybrid database, if one exists.
	 * 
	 *  The old database is only read, never modified — it stays on disk so nothing
	 *  is lost if the result is unsatisfactory.
	 */
	importLegacyMetadata: (legacyDbPath: string) => typedError<SalvageReport, AppError>(__TAURI_INVOKE("import_legacy_metadata", { legacyDbPath })),
	/**  Metadata previously resolved for this filename, if any. */
	legacyMetadataFor: (fileName: string) => typedError<string | null, AppError>(__TAURI_INVOKE("legacy_metadata_for", { fileName })),
	markLegacyConsumed: (fileName: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_legacy_consumed", { fileName })),
	saveAnnotation: (annotation: NewAnnotation) => typedError<null, AppError>(__TAURI_INVOKE("save_annotation", { annotation })),
	annotationsForSource: (sha256: string) => typedError<Annotation[], AppError>(__TAURI_INVOKE("annotations_for_source", { sha256 })),
	allAnnotations: (limit: number | null, offset: number | null) => typedError<Annotation[], AppError>(__TAURI_INVOKE("all_annotations", { limit, offset })),
	deleteAnnotation: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_annotation", { id })),
	deleteImportedAnnotations: (sha256: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_imported_annotations", { sha256 })),
	annotationLabels: () => typedError<AnnotationLabel[], AppError>(__TAURI_INVOKE("annotation_labels")),
	saveLabel: (label: AnnotationLabel) => typedError<null, AppError>(__TAURI_INVOKE("save_label", { label })),
	deleteLabel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_label", { id })),
	saveReadingPosition: (sha256: string, page: number, scroll: number | null, scale: string | null) => typedError<null, AppError>(__TAURI_INVOKE("save_reading_position", { sha256, page, scroll, scale })),
	readingPosition: (sha256: string) => typedError<number | null, AppError>(__TAURI_INVOKE("reading_position", { sha256 })),
	pathForSource: (sha256: string) => typedError<string | null, AppError>(__TAURI_INVOKE("path_for_source", { sha256 })),
	sourceForPath: (path: string) => typedError<string | null, AppError>(__TAURI_INVOKE("source_for_path", { path })),
	saveAnnotationImage: (id: string, png: number[]) => typedError<null, AppError>(__TAURI_INVOKE("save_annotation_image", { id, png })),
	annotationImage: (id: string) => typedError<number[] | null, AppError>(__TAURI_INVOKE("annotation_image", { id })),
	/**
	 *  Embed a mark's text so it can be found by meaning later.
	 * 
	 *  The embedding happens here rather than in the frontend for the same reason
	 *  search does: `embed_texts` is synchronous ONNX inference, and a 384-float
	 *  vector has no business crossing the IPC boundary in either direction when
	 *  only the database needs it.
	 * 
	 *  Skipped when the text has not changed. Recolouring a highlight or moving it
	 *  to another label should not cost an inference.
	 */
	embedAnnotation: (id: string, text: string) => typedError<boolean, AppError>(__TAURI_INVOKE("embed_annotation", { id, text })),
	/**
	 *  Give every mark that has none a vector, so it can be found by meaning.
	 * 
	 *  Marks are embedded as they are made, and that can fail quietly — a library
	 *  not open yet, a model still loading, a save racing a project switch. A
	 *  highlight must never be lost to a failed embedding, so the failure is
	 *  swallowed; the cost is that the mark is then missing from every search by
	 *  meaning with nothing to say so. This is the way back.
	 * 
	 *  Returns how many were embedded, so the caller can say what happened rather
	 *  than leave another silence.
	 */
	embedPendingAnnotations: () => typedError<number, AppError>(__TAURI_INVOKE("embed_pending_annotations")),
	/**
	 *  Find marks, by their words or by what they are about.
	 * 
	 *  Deliberately separate from `search_sources`. A passage from a paper and a
	 *  note the researcher wrote are not the same kind of thing — one is quotable,
	 *  the other is a judgement already made — and a 12-word note does not produce
	 *  a cosine score comparable with a 100-word passage, so merging the two into
	 *  one ranked list would be quietly wrong in a way nobody could see.
	 */
	searchAnnotations: (query: string, limit: number | null, semantic: boolean | null) => typedError<ScoredAnnotation[], AppError>(__TAURI_INVOKE("search_annotations", { query, limit, semantic })),
	restoreDefaultLabels: () => typedError<number, AppError>(__TAURI_INVOKE("restore_default_labels")),
	nameLabelsAfterColours: () => typedError<number, AppError>(__TAURI_INVOKE("name_labels_after_colours")),
};

/* Types */
/**
 *  A reading mark: a highlight, an area snapshot, or a note pinned to a page.
 * 
 *  Anchored twice over. `rects` draws it immediately and survives zoom, because
 *  it is stored in PDF user space rather than screen pixels. `quote` with the
 *  text either side finds it again when the geometry stops agreeing, and is
 *  also what makes the passage searchable rather than merely positioned.
 */
export type Annotation = {
	id: string,
	sha256: string,
	/**  'highlight' | 'area' | 'page-note' */
	kind: string,
	label_id: string | null,
	page: number,
	/**  JSON array of `{x, y, w, h}` in PDF user space; None for a page note. */
	rects: string | null,
	quote: string | null,
	prefix: string | null,
	suffix: string | null,
	char_start: number | null,
	char_end: number | null,
	note: string | null,
	/**  'fill' | 'underline' — how the mark is drawn, not what it means. */
	style: string,
	/**  The page number the paper itself prints, when it differs from the sheet. */
	page_label: string | null,
	/**
	 *  'erti' | 'imported' — so highlights brought in from Zotero or Preview
	 *  can be told apart, and undone in one action.
	 */
	origin: string,
	created_at: string,
	updated_at: string,
};

/**  What a highlight colour means. */
export type AnnotationLabel = {
	id: string,
	name: string,
	/**
	 *  `H S% L%`, matching the theme tokens rather than a hex string, so a
	 *  label sits in the same colour system as the rest of the interface.
	 */
	colour: string,
	position: number,
	enabled: boolean,
};

/**  An error on its way to the webview. */
export type AppError = {
	kind: ErrorKind,
	/**  A sentence a person can read, already saying what to do where possible. */
	message: string,
};

export type CompileResult = {
	ok: boolean,
	/**  Path to the PDF, when one was produced. */
	pdf: string | null,
	/**  The engine's output, kept whether or not it succeeded. */
	log: string,
};

/**
 *  The model that produced the stored vectors, if any are stored yet.
 *  Which model produced the stored vectors.
 */
export type EmbeddingMeta = {
	model_id: string,
	dims: number,
};

export type EmbeddingResult = {
	chunk_text: string,
	embedding: (number | null)[],
};

/**  What sort of failure this was, for the interface to act on. */
export type ErrorKind = 
/**  A file, source or record that isn't there (any more). */
"NotFound" | 
/**  The operating system refused; the message says which setting fixes it. */
"PermissionDenied" | 
/**  The request itself was malformed or out of range. */
"InvalidInput" | 
/**  It clashes with the current state: already exists, not open yet. */
"Conflict" | 
/**  Some other filesystem failure. */
"Io" | 
/**  The library or project database failed. */
"Database" | 
/**  The embedding model failed. */
"Model" | 
/**  A network request failed. */
"Network" | 
/**  A bug: something that should not happen. */
"Internal";

export type FileItem = {
	name: string,
	path: string,
	is_dir: boolean,
	children: FileItem[] | null,
};

/**
 *  An annotation on its way in. The id is chosen by the caller so the same
 *  record keeps its identity through an export and back.
 */
export type NewAnnotation = {
	id: string,
	sha256: string,
	kind: string,
	label_id?: string | null,
	page: number,
	rects?: string | null,
	quote?: string | null,
	prefix?: string | null,
	suffix?: string | null,
	char_start?: number | null,
	char_end?: number | null,
	note?: string | null,
	style?: string | null,
	page_label?: string | null,
	origin?: string | null,
};

export type NewChunk = {
	text: string,
	embedding: (number | null)[],
	page_start?: number | null,
	page_end?: number | null,
	section?: string | null,
	char_start?: number | null,
	char_end?: number | null,
};

export type SalvageReport = {
	/**  Rows carried forward. */
	imported: number,
	/**
	 *  Rows a previous run already carried forward. Reported separately so a
	 *  repeat launch does not claim new work.
	 */
	already_present: number,
	/**  Rows skipped because their metadata was a `'{}'` placeholder or absent. */
	skipped_empty: number,
	/**  Files in the old database that were registered but never processed. */
	skipped_unprocessed: number,
};

/**  A mark, ranked against something the researcher is looking for. */
export type ScoredAnnotation = {
	/**  Cosine similarity for a semantic search; 1.0 for a literal match. */
	similarity: number | null,
	/**  False when the mark is on a paper outside the open project's source set. */
	in_project: boolean,
	/**  The paper's filename, so a result can name where it came from. */
	file_name: string | null,
} & Annotation;

export type ScoredChunk = {
	sha256: string,
	/**
	 *  Position of the chunk within its source. `(sha256, idx)` is the chunk's
	 *  primary key, and the only stable identity a result has — two chunks from
	 *  one PDF share a hash.
	 */
	idx: number,
	text: string,
	page_start: number | null,
	section: string | null,
	similarity: number | null,
	/**  False when the chunk comes from outside the current project's source set. */
	in_project: boolean,
};

export type Source = {
	sha256: string,
	file_name: string,
	path: string | null,
	/**  CSL-JSON, with any project-local override already applied. */
	csl_json: string | null,
	zotero_type: string | null,
	doi: string | null,
	resolved_via: string | null,
	state: string,
	last_error: string | null,
};

export type TexToolchain = {
	/**  The engine found, if any. */
	engine: string | null,
	/**  Whether BibTeX or Biber is available to resolve citations. */
	bibliography: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

